### ISSUE TITLE
Use OurPkgVersion on dist.ini

### ISSUE THREAD

**Issue by glasswalk3r** [cpan-testers/cpantesters-web#2]
Is acceptable for this project to use [PkgOurVersion](http://search.cpan.org/~plicease/Dist-Zilla-Plugin-OurPkgVersion-0.10/lib/Dist/Zilla/Plugin/OurPkgVersion.pm) plug-in for Dist::Zilla?

We could use it to control the version easily from the dist.ini. There are just a few files with `$VERSION` declared:

```
$ ack '\$VERSION'
dist.ini
106:; NextRelease acts *during* pre-release to write $VERSION and

lib/CPAN/Testers/Web.pm
2:our $VERSION = '0.001';

lib/CPAN/Testers/Web/Base.pm
3:our $VERSION = '0.001';

bin/cpantesters-web
3:our $VERSION = '0.001';
```

**Comment by preaction** [comment]
No. That's what I used to use before I switched to what I'm using now. The difference between the two is that in the rare occasion where the distribution version matters in the tests (for a web app, in the `<meta name="generator" />` tag), we don't have to make one up, and the distribution is fully properly installable from the git checkout without Dist::Zilla (you don't install a distribution that lacks a version number).
