### ISSUE TITLE
Figure out why CPAN Testers is being blocked by Cisco

### ISSUE THREAD

**Issue by preaction** [cpan-testers/cpantesters-web#25]
Grant Street Group is having trouble accessing CPAN Testers websites (all sites in the domain `cpantesters.org`). They opened a ticket with Cisco, and the Cisco tech said:

> Our Security Research Team has decided to keep this domain blocked at this time. This is due to the domain hosting adware and being called on by various malware callouts.

Since we don't host adware, I suspect we have to figure out what "malware callouts" are and how to remove ourselves from them.

https://talosintelligence.com/reputation_center/lookup?search=cpantesters.org#ip-addresses says we have a "poor" reputation, but doesn't say why because why would it provide useful information? It does have a link to "dispute" the reputation, but the wording of the tech's response makes me think that'll go exactly nowhere (but I get to try anyway, because this is apparently how things work now, as opaquely as possible).

**Comment by preaction** [comment]
Matthew Gray at Grant Street continued following up with Cisco, and they revealed this link which purports to show which malware we are hosting: https://www.virustotal.com/en/domain/matrix.cpantesters.org/information/ We should do some due diligence and see what's actually going on here.

**Comment by preaction** [comment]
![screen shot 2019-01-02 at 9 30 12 am](https://user-images.githubusercontent.com/53707/50599359-7d6f8800-0e73-11e9-9220-01fb400b8936.png)
![screen shot 2019-01-02 at 9 47 20 am](https://user-images.githubusercontent.com/53707/50599364-819ba580-0e73-11e9-9c3e-3a81dc1f8baf.png)

**Comment by eserte** [comment]
I see that matrix.cpantesters.org is mentioned here. What does the virustotal information mean? Is it that there are viruses in the wild which include matrix.cpantesters.org URLs in it? What can we do about it?

**Comment by preaction** [comment]
The VirusTotal site is saying that viruses are using matrix.cpantesters.org, not that matrix.cpantesters.org is hosting malware itself. The site does not host any of those files, so I have no clue how to pursue this.

**Comment by barbie** [comment]
It would seem the only way for them to "intelligently" fix this stupid
rule, is to wait until the malware writers start embedding cisco.com in
their code! Is microsoft.com blocked I wonder? Being the recipient of a
firebomb does not make the victim an arsonist!

Once malware writers discover this horrible logic flaw, how many sites are
they going to get blacklisted just because someone decides to list them!

Good luck Doug :)

-- 
Birmingham.pm - http://birmingham.pm.org
YAPC Surveys - http://yapc-surveys.org
Perl Jam - http://perljam.info

**Comment by preaction** [comment]
So, I'd love to file a ticket with Talos, but when I try to, I get a 500 error (which is about what I was expecting).
<img width="778" alt="screen shot 2019-01-10 at 7 00 10 pm" src="https://user-images.githubusercontent.com/53707/51006835-a2ff3000-150a-11e9-835c-67f2120a5188.png">
<img width="721" alt="screen shot 2019-01-10 at 7 00 16 pm" src="https://user-images.githubusercontent.com/53707/51006836-a2ff3000-150a-11e9-898e-bb4fe871ac14.png">

**Comment by preaction** [comment]
Turns out that was a Safari problem, though how I'm supposed to know that is anyone's guess. When I used Chrome instead, the form submitted correctly. Now we wait until they tell me that there's nothing they can do.

**Comment by preaction** [comment]
Looks like my ticket worked and GSG is not blocked from CPAN Testers anymore.
